spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://lamdt-mysql-server.database.windows.net:1433;database=mysql-db
    username: lamdt@lamdt-mysql-server
    password: Bxz571993
    platform: mssql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update


